### ISSUE TITLE
UI for User to Change Their Location

### ISSUE THREAD

**Issue by gracepotma** [openmrs/openmrs-esm-primary-navigation#35]
After logging in and selecting a location from the Homepage Location Widget, users should be able to change their location from the top menu:  
![image](https://user-images.githubusercontent.com/67400059/86499990-fd193400-bd42-11ea-9fcb-9e41dfd1ccf7.png)

2 alternatives:

1. The users will be able to change their location without navigating away from the page via a pre-populated drop-down list of available locations based on the type of user.  (see example below) 
![image](https://user-images.githubusercontent.com/67400059/86499998-0f936d80-bd43-11ea-9cb0-b9c8d7a269c3.png)

 

If changing the location changes the content of the page the user is at, the user should be sent to the Home Page.  

2. If the users click on the location at the top of the page, they will be sent to the Location widget in the Home Page [https://www.openmrs-spa.org/openmrs/spa/login/location] (see below): 

![image](https://user-images.githubusercontent.com/67400059/86500009-1f12b680-bd43-11ea-812f-cd9d6217ba71.png)

**Comment by FlorianRappl** [comment]
> This is done on primary navigation

Its fine - we can always transfer.

**Comment by FlorianRappl** [comment]
This just shipped. Thanks to @donaldkibet for putting in the work. Much appreciated :beers:!
